namespace NFK001.Business.NFK001
{
    public class NFK001DALSQL
    {
        public static string Get()
        {
            return @"WITH VIGORA
AS (
   	SELECT A.CODFILEMP
      		 , A.CODFRN
      		 , I.CODCID
      		 , I.CODMER
      		 , MAX(DATHRAAPVLSTPCOFRN) DATHRAAPVLSTPCOFRN
   	FROM MRT.T0114109 A
   	INNER JOIN MRT.T0114117 I ON A.NUMSEQLSTPCOFRN = I.NUMSEQLSTPCOFRN
   	INNER JOIN MRT.T0153541 B ON A.CODFILEMP = B.CODFILEMP
      		AND A.CODFRN = B.CODFRN
      		AND B.INDCPRPCPFRN = 1
      		AND A.DATINIVGRLSTPCO <= TRUNC(SYSDATE)
   	WHERE A.DATHRAAPVLSTPCOFRN IS NOT NULL
      		--AND I.PERICMITE IS NOT NULL
      		AND A.CODFILEMP = 1
   	GROUP BY A.CODFILEMP
      		   , A.CODFRN
      		   , I.CODCID
      		   , I.CODMER
   	)
   	,EM_APROVACAO
AS (
   	SELECT A.CODFILEMP
      		 , A.CODFRN
      		 , I.CODCID
      		 , I.CODMER
      		 , MAX(DATCADLSTPCOFRN) DATCADLSTPCOFRN
   	FROM VIGORA V
   	INNER JOIN MRT.T0114109 A ON A.CODFRN = V.CODFRN
      		AND A.CODFILEMP = V.CODFILEMP
   	INNER JOIN MRT.T0114117 I ON A.NUMSEQLSTPCOFRN = I.NUMSEQLSTPCOFRN
      		AND I.CODCID = V.CODCID
      		AND I.CODMER = V.CODMER
   	WHERE A.DATCADLSTPCOFRN >= V.DATHRAAPVLSTPCOFRN
      		AND A.CODFNCAPV > 0
      		AND A.DATHRAAPVLSTPCOFRN IS NULL
   	GROUP BY A.CODFILEMP
      		   , A.CODFRN
      		   , I.CODCID
      		   , I.CODMER
   	)
SELECT A.NUMSEQLSTPCOFRN
      	, A.CODFRN
      	, A.CODFILEMP
      	, B.CODCID
      	, CID.CODESTUNI
      	, B.CODMER
      	, cast(B.VLRPCOLSTPCO AS NUMERIC(13, 4)) VLRPCOLSTPCO
      	, NVL(B.PERIPILSTPCO, 0) PERIPILSTPCO
      	, A.TIPFRTLSTPCO TIPFRT
      	, NVL(B.PERICMITE, 0) PERICMITE
      	, NVL(B.PERRDCALQICM, 0)
      	, A.DATHRAAPVLSTPCOFRN
      	, DECODE(A.DATHRAAPVLSTPCOFRN, NULL, 2, 1) CODSTAAPV
FROM MRT.T0114109 A
INNER JOIN MRT.T0114117 B ON A.NUMSEQLSTPCOFRN = B.NUMSEQLSTPCOFRN
INNER JOIN MRT.T0100426 F ON F.CODFRN = A.CODFRN
INNER JOIN MRT.T0100086 M ON M.CODMER = B.CODMER
INNER JOIN MRT.T0100035 CID ON CID.CODCID = B.CODCID
LEFT JOIN VIGORA V ON A.CODFILEMP = V.CODFILEMP
   	AND A.CODFRN = V.CODFRN
   	AND B.CODCID = V.CODCID
   	AND V.CODMER = B.CODMER
   	AND A.DATHRAAPVLSTPCOFRN = V.DATHRAAPVLSTPCOFRN
LEFT JOIN EM_APROVACAO P ON A.CODFILEMP = P.CODFILEMP
   	AND A.CODFRN = P.CODFRN
   	AND B.CODCID = P.CODCID
   	AND B.CODMER = P.CODMER
   	AND A.DATCADLSTPCOFRN = P.DATCADLSTPCOFRN
WHERE V.CODMER IS NOT NULL
   	OR P.CODMER IS NOT NULL
ORDER BY A.CODFILEMP
   	   , A.NUMSEQLSTPCOFRN DESC

        OFFSET 20 ROWS FETCH NEXT 15 ROWS ONLY";
        }

        public static string Update()
        {
            return @"INSERT INTO MRT.MOVLSTPCOSMLCMP (
   	DATREFOPE
   	,CODFILEMPEPD
   	,CODMER
   	,NUMSEQLSTPCOFRN
   	,CODSTAAPV
   	,CODFRN
   	,CODCID
   	,CODESTUNI
   	,VLRPCOLSTPCO
   	,VLRPCOLSTPCODSC
   	,PERIPILSTPCO
   	,PERICMITE
   	,TIPFRT
   	,DATHRAAPVLSTPCOFRN
    	,PERALQICMNOTFSC
   	,INDORIMERFRN
   	,PERTBTICMFNDPBR
   	)
VALUES (
    :DATAPLANO
   ,:CODFILEMP
   ,:CODMER
   ,:NUMSEQLSTPCOFRN
   ,:CODSTAAPV
   ,:CODFRN
   ,:CODCID
   ,:CODESTUNI
   ,:VLRPCOLSTPCO
   ,:VLRPCOLSTPCO
   ,:PERIPILSTPCO
   ,:PERICMITE
   ,:TIPFRT
   ,:DATHRAAPVLSTPCOFRN
   ,:PERALQICMNOTFSC
   ,:INDORIMERFRN
   ,:PERTBTICMFNDPBR
   	)";
        }
    }
}
